apiVersion: apps/v1
kind: Deployment
metadata:
  name: printer-3d
  namespace: zelig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: printer-3d
  template:
    metadata:
      labels:
        app: printer-3d
    spec:
      containers:
      - name: printer-3d
        image: erin/zelig:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: printer-config-volume
            mountPath: /config.yaml
            subPath: config.yaml
        env:
          - name: CONFIG_PATH
            value: /config.yaml
      volumes:
        - name: printer-config-volume
          configMap:
            name: printer-3d-config