apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
  namespace: zelig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
      - name: ai-model
        image: ghcr.io/suse-technical-marketing/zelig:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: ai-model-config-volume
            mountPath: /config.yaml  # Mounts config at /config.yaml
            subPath: config.yaml
        env:
          - name: CONFIG_PATH
            value: /config.yaml
      volumes:
        - name: ai-model-config-volume
          configMap:
            name: ai-model-config