apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-of-sale
  namespace: zelig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-of-sale
  template:
    metadata:
      labels:
        app: point-of-sale
    spec:
      containers:
      - name: point-of-sale
        image: ghcr.io/suse-technical-marketing/zelig:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: pos-config-volume
            mountPath: /config.yaml
            subPath: config.yaml
        env:
          - name: CONFIG_PATH
            value: /config.yaml
      volumes:
        - name: pos-config-volume
          configMap:
            name: point-of-sale-config