apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zelig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: erin/zelig-frontend:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: frontend-config-volume
            mountPath: /config.yaml  # Mounts app config at /config.yaml
            subPath: config.yaml
          - name: modules-config-volume
            mountPath: /modules-config.yaml  # Mounts module config at /modules-config.yaml
            subPath: modules-config.yaml
        env:
          - name: CONFIG_PATH
            value: /config.yaml
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config
        - name: modules-config-volume
          configMap:
            name: frontend-modules-config